---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - _misc/*
    - bin/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Naming/FileName:
  Exclude:
    - lib/rails-event-sourcing.rb
