---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  Exclude:
    - _misc/*
    - bin/*
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Naming/FileName:
  Exclude:
    - lib/rails-event-sourcing.rb

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleMemoizedHelpers:
  Max: 8

Style/GuardClause:
  Enabled: false
